services:
  consultation-service:
    build:
      context: ./consultation
      dockerfile: Dockerfile
    container_name: consultation-service
    env_file:
      - ./consultation/.env
    ports:
      - "8001:8000"
    networks:
      - veterinary-network

  feedback-service:
    build:
      context: ./feedbackvet
      dockerfile: Dockerfile
    container_name: feedback-service
    env_file:
      - ./feedbackvet/.env
    ports:
      - "8002:8000"
    networks:
      - veterinary-network

  vet-service:
    build:
      context: ./vet
      dockerfile: Dockerfile
    container_name: vet-service
    env_file:
      - ./vet/.env
    ports:
      - "8003:8000"
    networks:
      - veterinary-network

networks:
  veterinary-network:
    driver: bridge
